### ISSUE TITLE
OpenBSD package emacs-24.5p2-no_x11 not found

### ISSUE THREAD

**Issue by ochko** [reallyenglish/ansible-role-editors#7]
correct one is emacs-24.5p5-no_x11

http://ftp.openbsd.org/pub/OpenBSD/6.0/packages/amd64/

**Comment by ochko** [comment]
Incomplete WIP in #8.

Unassigned myself because I won't be able to work on this next few weeks

**Comment by trombik** [comment]
this role should not be used. use `ansible-role-vim` and/or `ansible-role-emacs`.
